### ISSUE TITLE
Cannot import with python2.7

### ISSUE THREAD

**Issue by autra** [niolabs/nio#158]
# Description

with python2.7, pip install nio succeeds, yet importing it does not work:

```
>>> import nio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/augustin/.local/lib/python2.7/site-packages/nio/__init__.py", line 1, in <module>
    from nio.block.base import Block
  File "/home/augustin/.local/lib/python2.7/site-packages/nio/block/base.py", line 12, in <module>
    from nio.command import command
  File "/home/augustin/.local/lib/python2.7/site-packages/nio/command/__init__.py", line 1, in <module>
    from nio.command.decorator import command
  File "/home/augustin/.local/lib/python2.7/site-packages/nio/command/decorator.py", line 1, in <module>
    from nio.command.base import Command
  File "/home/augustin/.local/lib/python2.7/site-packages/nio/command/base.py", line 29
    def __init__(self, id, *params, title=None, method=None):
                                        ^
SyntaxError: invalid syntax
```

# Context

Trying to install weechat-matrix on my stretch box, see https://github.com/poljar/weechat-matrix/issues/132.

Thanks!

**Comment by autra** [comment]
I understand fixing things for python2.7 might not be very relevant. In this case, maybe the setup.py should indicate supported python version. That will help pip to pick the correct version when installing on python2.7 env.
